// Copyright (c) Michael Grier

//! Integration test: read a real `.binlog` file produced by `dotnet build /bl`
//! and verify that the sequential reader can parse every event without error.

use std::fs::File;

use munin::{BinaryLogRecordKind, BinlogEvent, BinlogIndex, BinlogReader};

/// Path to the test fixture generated by building a minimal .NET console app.
const HELLO_BINLOG: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/data/hello.binlog");

#[test]
fn read_all_events_from_real_binlog() {
    let file = File::open(HELLO_BINLOG).expect("missing test fixture: hello.binlog");
    let mut reader = BinlogReader::open(file).expect("failed to open binlog");

    // Header version must be in our supported range.
    let version = reader.header().file_format_version;
    assert!(version >= 18, "expected version >= 18, got {version}");

    let events = reader.read_all_events().expect("failed to read events");

    // A successful build of a minimal project produces at least a handful of
    // events: BuildStarted, ProjectEvaluationStarted/Finished,
    // ProjectStarted/Finished, TargetStarted/Finished, BuildFinished, etc.
    assert!(
        events.len() > 10,
        "expected more than 10 events, got {}",
        events.len()
    );

    // There must be exactly one BuildStarted event.
    let build_started_count = events
        .iter()
        .filter(|e| matches!(e, BinlogEvent::BuildStarted(_)))
        .count();
    assert_eq!(
        build_started_count, 1,
        "expected exactly 1 BuildStarted event"
    );

    // The last event must be BuildFinished.
    assert!(
        matches!(events.last().unwrap(), BinlogEvent::BuildFinished(_)),
        "last event should be BuildFinished"
    );

    // BuildFinished should indicate success.
    if let BinlogEvent::BuildFinished(ref bf) = events.last().unwrap() {
        assert!(bf.succeeded, "build should have succeeded");
    }

    // There should be at least one ProjectStarted and one ProjectFinished.
    let project_started_count = events
        .iter()
        .filter(|e| matches!(e, BinlogEvent::ProjectStarted(_)))
        .count();
    let project_finished_count = events
        .iter()
        .filter(|e| matches!(e, BinlogEvent::ProjectFinished(_)))
        .count();
    assert!(
        project_started_count >= 1,
        "expected at least 1 ProjectStarted, got {project_started_count}"
    );
    assert_eq!(
        project_started_count, project_finished_count,
        "ProjectStarted/Finished count mismatch"
    );

    // There should be at least one TargetStarted event.
    let target_started_count = events
        .iter()
        .filter(|e| matches!(e, BinlogEvent::TargetStarted(_)))
        .count();
    assert!(
        target_started_count >= 1,
        "expected at least 1 TargetStarted"
    );

    // String table should have been populated.
    assert!(
        !reader.strings().is_empty(),
        "string table should not be empty"
    );
}

#[test]
fn string_table_contains_project_path() {
    let file = File::open(HELLO_BINLOG).expect("missing test fixture: hello.binlog");
    let mut reader = BinlogReader::open(file).expect("failed to open binlog");
    let _ = reader.read_all_events().expect("failed to read events");

    // The string table should contain the project file name.
    let has_csproj = (0..reader.strings().len())
        .filter_map(|i| reader.strings().get(i as i32).ok().flatten())
        .any(|s: &str| s.contains("HelloBinlog.csproj"));
    assert!(has_csproj, "string table should contain the .csproj path");
}

#[test]
fn events_have_consistent_record_kinds() {
    let file = File::open(HELLO_BINLOG).expect("missing test fixture: hello.binlog");
    let mut reader = BinlogReader::open(file).expect("failed to open binlog");
    let events = reader.read_all_events().expect("failed to read events");

    // Verify that record_kind() returns the correct variant for every event.
    for event in &events {
        let kind = event.record_kind();
        // Round-trip: the kind discriminant must match the variant.
        match event {
            BinlogEvent::BuildStarted(_) => {
                assert_eq!(kind, munin::BinaryLogRecordKind::BuildStarted)
            }
            BinlogEvent::BuildFinished(_) => {
                assert_eq!(kind, munin::BinaryLogRecordKind::BuildFinished)
            }
            BinlogEvent::ProjectStarted(_) => {
                assert_eq!(kind, munin::BinaryLogRecordKind::ProjectStarted)
            }
            BinlogEvent::ProjectFinished(_) => {
                assert_eq!(kind, munin::BinaryLogRecordKind::ProjectFinished)
            }
            _ => {
                // For the remaining variants, just verify record_kind()
                // doesn't panic and returns a non-zero value.
                let _ = kind;
            }
        }
    }
}

#[test]
fn next_event_by_event_matches_read_all() {
    // Read events one at a time and compare with read_all_events.
    let file1 = File::open(HELLO_BINLOG).expect("missing test fixture");
    let mut reader1 = BinlogReader::open(file1).expect("failed to open binlog");
    let all_events = reader1.read_all_events().expect("read_all failed");

    let file2 = File::open(HELLO_BINLOG).expect("missing test fixture");
    let mut reader2 = BinlogReader::open(file2).expect("failed to open binlog");

    let mut count = 0;
    while let Some(event) = reader2.next_event().expect("next_event failed") {
        assert_eq!(
            event.record_kind(),
            all_events[count].record_kind(),
            "event {} record kind mismatch",
            count
        );
        count += 1;
    }
    assert_eq!(count, all_events.len(), "event count mismatch");
}

#[test]
fn nvl_table_populated_from_real_binlog() {
    let file = File::open(HELLO_BINLOG).expect("missing test fixture");
    let mut reader = BinlogReader::open(file).expect("failed to open binlog");
    let _ = reader.read_all_events().expect("read_all failed");

    // A real build usually has name-value lists (global/project properties).
    // The NVL table should have at least one entry.
    assert!(
        !reader.nvl_table().is_empty(),
        "NVL table should not be empty for a real build"
    );
}

#[test]
fn extract_archives_does_not_error() {
    let file = File::open(HELLO_BINLOG).expect("missing test fixture");
    let mut reader = BinlogReader::open(file).expect("failed to open binlog");
    let _ = reader.read_all_events().expect("read_all failed");

    // extract_archives should not error even if there are no archives.
    let entries = reader.extract_archives().expect("extract_archives failed");

    // If there are archives, every entry should have a non-empty path.
    for entry in &entries {
        assert!(
            !entry.path.is_empty(),
            "archive entry path should not be empty"
        );
    }
}

#[test]
fn build_started_has_nonempty_environment() {
    let file = File::open(HELLO_BINLOG).expect("missing test fixture");
    let mut reader = BinlogReader::open(file).expect("failed to open binlog");
    let events = reader.read_all_events().expect("read_all failed");

    let bs = events
        .iter()
        .find_map(|e| match e {
            BinlogEvent::BuildStarted(bs) => Some(bs),
            _ => None,
        })
        .expect("no BuildStarted event found");

    let env = bs.environment.as_ref().expect("environment should be Some");
    assert!(
        !env.is_empty(),
        "BuildStarted.environment should not be empty"
    );
}

#[test]
fn no_error_events_in_successful_build() {
    let file = File::open(HELLO_BINLOG).expect("missing test fixture");
    let mut reader = BinlogReader::open(file).expect("failed to open binlog");
    let events = reader.read_all_events().expect("read_all failed");

    let error_count = events
        .iter()
        .filter(|e| matches!(e, BinlogEvent::Error(_)))
        .count();
    assert_eq!(
        error_count, 0,
        "successful build should have no Error events"
    );
}

#[test]
fn message_events_present() {
    let file = File::open(HELLO_BINLOG).expect("missing test fixture");
    let mut reader = BinlogReader::open(file).expect("failed to open binlog");
    let events = reader.read_all_events().expect("read_all failed");

    let message_count = events
        .iter()
        .filter(|e| matches!(e, BinlogEvent::Message(_)))
        .count();
    assert!(
        message_count > 0,
        "expected at least one Message event in a real build"
    );
}

#[test]
fn target_and_task_events_paired() {
    let file = File::open(HELLO_BINLOG).expect("missing test fixture");
    let mut reader = BinlogReader::open(file).expect("failed to open binlog");
    let events = reader.read_all_events().expect("read_all failed");

    let target_started = events
        .iter()
        .filter(|e| matches!(e, BinlogEvent::TargetStarted(_)))
        .count();
    let target_finished = events
        .iter()
        .filter(|e| matches!(e, BinlogEvent::TargetFinished(_)))
        .count();
    assert_eq!(
        target_started, target_finished,
        "TargetStarted/Finished should be paired"
    );

    let task_started = events
        .iter()
        .filter(|e| matches!(e, BinlogEvent::TaskStarted(_)))
        .count();
    let task_finished = events
        .iter()
        .filter(|e| matches!(e, BinlogEvent::TaskFinished(_)))
        .count();
    assert_eq!(
        task_started, task_finished,
        "TaskStarted/Finished should be paired"
    );
}

// ---------------------------------------------------------------------------
// BinlogIndex integration tests — seekable random-access patterns
// ---------------------------------------------------------------------------

#[test]
fn index_opens_real_binlog() {
    let file = File::open(HELLO_BINLOG).expect("missing test fixture");
    let index = BinlogIndex::open(file).expect("failed to open index");

    assert!(
        index.len() > 10,
        "expected more than 10 events, got {}",
        index.len()
    );
    assert!(!index.is_empty());
    assert!(index.header().file_format_version >= 18);
}

#[test]
fn index_matches_sequential_reader() {
    // The index and sequential reader must produce identical events.
    let file1 = File::open(HELLO_BINLOG).expect("missing test fixture");
    let mut reader = BinlogReader::open(file1).expect("failed to open reader");
    let seq_events = reader.read_all_events().expect("read_all failed");

    let file2 = File::open(HELLO_BINLOG).expect("missing test fixture");
    let index = BinlogIndex::open(file2).expect("failed to open index");

    assert_eq!(
        index.len(),
        seq_events.len(),
        "index and reader event counts must match"
    );

    // Verify every event has the same record kind.
    for (i, seq_event) in seq_events.iter().enumerate() {
        let meta = index.meta(i).expect("meta out of range");
        assert_eq!(
            meta.record_kind,
            seq_event.record_kind(),
            "event {i} record kind mismatch"
        );
    }
}

#[test]
fn index_random_access_deserialization() {
    let file = File::open(HELLO_BINLOG).expect("missing test fixture");
    let index = BinlogIndex::open(file).expect("failed to open index");

    // Access the first and last events by index — just verify they deserialize.
    let first = index.get(0).expect("get(0) failed").expect("no event at 0");
    let _ = first.record_kind(); // smoke-test

    let last_idx = index.len() - 1;
    let last = index
        .get(last_idx)
        .expect("get(last) failed")
        .expect("no event at last");
    let _ = last.record_kind();

    // Access a middle event.
    let mid_idx = index.len() / 2;
    let mid = index
        .get(mid_idx)
        .expect("get(mid) failed")
        .expect("no event at mid");
    assert_eq!(
        mid.record_kind(),
        index.meta(mid_idx).unwrap().record_kind,
        "deserialized event kind must match meta"
    );

    // Out-of-range returns None.
    assert!(index.get(index.len() + 100).unwrap().is_none());
}

#[test]
fn index_get_all_matches_sequential() {
    let file1 = File::open(HELLO_BINLOG).expect("missing test fixture");
    let mut reader = BinlogReader::open(file1).expect("failed to open reader");
    let seq_events = reader.read_all_events().expect("read_all failed");

    let file2 = File::open(HELLO_BINLOG).expect("missing test fixture");
    let index = BinlogIndex::open(file2).expect("failed to open index");
    let idx_events = index.get_all().expect("get_all failed");

    assert_eq!(seq_events.len(), idx_events.len());
    for (i, (s, x)) in seq_events.iter().zip(idx_events.iter()).enumerate() {
        assert_eq!(
            s.record_kind(),
            x.record_kind(),
            "event {i} kind mismatch between reader and index"
        );
    }
}

#[test]
fn index_filter_by_record_kind() {
    let file = File::open(HELLO_BINLOG).expect("missing test fixture");
    let index = BinlogIndex::open(file).expect("failed to open index");

    // Exactly one BuildStarted.
    let bs = index.indices_by_kind(BinaryLogRecordKind::BuildStarted);
    assert_eq!(bs.len(), 1, "expected exactly 1 BuildStarted");

    // Exactly one BuildFinished.
    let bf = index.indices_by_kind(BinaryLogRecordKind::BuildFinished);
    assert_eq!(bf.len(), 1, "expected exactly 1 BuildFinished");

    // BuildFinished should come after BuildStarted.
    assert!(
        bf[0] > bs[0],
        "BuildFinished (index {}) should come after BuildStarted (index {})",
        bf[0],
        bs[0]
    );

    // At least one ProjectStarted.
    let ps = index.indices_by_kind(BinaryLogRecordKind::ProjectStarted);
    assert!(!ps.is_empty(), "expected at least 1 ProjectStarted");

    // ProjectStarted and ProjectFinished counts should match.
    let pf = index.indices_by_kind(BinaryLogRecordKind::ProjectFinished);
    assert_eq!(ps.len(), pf.len(), "ProjectStarted/Finished count mismatch");

    // At least one TargetStarted.
    let ts = index.indices_by_kind(BinaryLogRecordKind::TargetStarted);
    assert!(!ts.is_empty(), "expected at least 1 TargetStarted");

    // At least one Message.
    let msgs = index.indices_by_kind(BinaryLogRecordKind::Message);
    assert!(!msgs.is_empty(), "expected at least 1 Message event");
}

#[test]
fn index_byte_offsets_monotonically_increase() {
    let file = File::open(HELLO_BINLOG).expect("missing test fixture");
    let index = BinlogIndex::open(file).expect("failed to open index");

    let mut prev_offset = 0u64;
    for (i, meta) in index.iter_meta() {
        if i > 0 {
            assert!(
                meta.byte_offset > prev_offset,
                "event {i} offset {} should be after previous offset {}",
                meta.byte_offset,
                prev_offset
            );
        }
        prev_offset = meta.byte_offset;
    }
}

#[test]
fn index_context_based_queries() {
    let file = File::open(HELLO_BINLOG).expect("missing test fixture");
    let index = BinlogIndex::open(file).expect("failed to open index");

    // Find a ProjectStarted event to get a project_context_id.
    let ps_indices = index.indices_by_kind(BinaryLogRecordKind::ProjectStarted);
    assert!(!ps_indices.is_empty());

    let ps_event = index.get(ps_indices[0]).unwrap().unwrap();
    if let BinlogEvent::ProjectStarted(ref ps) = ps_event {
        // The ProjectStarted event itself has a context — use its project_context_id
        // to find all events in that project.
        if let Some(ctx) = &ps.fields.build_event_context {
            let project_events = index.indices_by_project_context(ctx.project_context_id);
            assert!(
                !project_events.is_empty(),
                "should find events for project_context_id {}",
                ctx.project_context_id
            );
            // The ProjectStarted itself should be among the results.
            assert!(
                project_events.contains(&ps_indices[0]),
                "project events should include the ProjectStarted event"
            );
        }
    }
}

#[test]
fn index_combined_query() {
    let file = File::open(HELLO_BINLOG).expect("missing test fixture");
    let index = BinlogIndex::open(file).expect("failed to open index");

    // Query with no filters returns all events.
    let all = index.query(None, None, None, None);
    assert_eq!(all.len(), index.len());

    // Query by kind only should match indices_by_kind.
    let by_kind = index.indices_by_kind(BinaryLogRecordKind::Message);
    let by_query = index.query(Some(BinaryLogRecordKind::Message), None, None, None);
    assert_eq!(by_kind, by_query);

    // Query with impossible kind returns empty.
    let empty = index.query(Some(BinaryLogRecordKind::EndOfFile), None, None, None);
    assert!(empty.is_empty());
}

#[test]
fn index_string_table_matches_reader() {
    let file1 = File::open(HELLO_BINLOG).expect("missing test fixture");
    let mut reader = BinlogReader::open(file1).expect("failed to open reader");
    let _ = reader.read_all_events().expect("read_all failed");

    let file2 = File::open(HELLO_BINLOG).expect("missing test fixture");
    let index = BinlogIndex::open(file2).expect("failed to open index");

    assert_eq!(
        reader.strings().len(),
        index.strings().len(),
        "string table lengths must match"
    );
}
